Add keyFormat "crt" support for RSA keyGen
smuellerDD/acvpparser pull request #75
Opened 2024-04-19 16:37 UTC by goatold

Add missing fields: dmp1, dmq1 and iqmp
Unmask field d for keyFormat "crt" case

2024-04-19 18:55 UTC, jvdsn requested changes

2024-04-19 18:55 UTC, jvdsn commented on backends/backend_openssl3.c
> +	// add test result fields that is required by keyFormat "crt"
These fields should only be set for the CRT key format. Right now this breaks vector processing for the standard key format.

2024-04-19 18:55 UTC, jvdsn commented on parser/parser_rsa.c
In `rsa_keygen_test_entries`, `FLAG_OP_RSA_CRT` should be added to all entries.

2024-04-19 20:49 UTC, goatold commented on parser/parser_rsa.c
FLAG_OP_RSA_CRT is only applicable to keyFormat "crt" fields.
d and (dmp1, dmq1, iqmp) should be mutually exclusive.

2024-04-19 21:05 UTC, jvdsn commented on parser/parser_rsa.c
`rsa_keygen_test_entries` is the input data, not the output data. All input data for keygen is applicable to both standard and CRT key formats.

2024-04-22 12:48 UTC, goatold commented on parser/parser_rsa.c
"d" is not included in the keyGen test case request
https://pages.nist.gov/ACVP/draft-celi-acvp-rsa.html

2024-04-23 23:27 UTC, jvdsn commented on parser/parser_rsa.c
That's why there is a `FLAG_OPTIONAL` flag

2024-04-23 23:29 UTC, jvdsn commented on parser/parser_rsa.c
`rsa_keygen_test_entries` contains the entries that are provided by the server to the IUT. It has the following values:
```
		{"xQ", ...},
		{"xQ1", ...},
		{"xQ2", ...},
		{"xQ", ...},
		{"xQ1", ...},
		{"xQ2", ...},
		{"e", ...},
```
The `FLAG_OP_RSA_CRT` must be added for all of them, otherwise the ACVP parser will not read these values for CRT keyGen cases

2024-04-25 13:36 UTC, jvdsn commented on parser/parser_rsa.c
Why do you say that `rsa_keygen_test_entries` contains output data?

2024-04-25 13:59 UTC, goatold commented on parser/parser_rsa.c
My mistake: 
rsa_keygen_test_entries specifies the input data 
rsa_keygen_testresult_entries specifies the output data

2024-04-25 14:10 UTC, goatold commented on parser/parser_rsa.c
Thanks @jvdsn for the comments. I misunderstood you previously. FLAG_OP_RSA_CRT is now added to all items in rsa_keygen_test_entries.

2024-04-26 06:33 UTC, smuellerDD commented
Applied, thanks

2024-04-26 06:33 UTC, closed without merging